### ISSUE TITLE
"Waiting for Server" or whatever

### ISSUE THREAD

**Issue by Fortist** [thebrightspark/S.T.E.M#15]
When leaving a memory chip with iron on it in a matter creator, closing the game and coming back, on the chip and in the matter scanner do they both have the message of "Waiting for the recipe from the server" or something.

**Comment by thebrightspark** [comment]
Does it happen for any other items on the memory chip?
And is this in single player or on a server?

The reason that happens is because all of the recipes are requested from the server when needed and then cached on the client. When awaiting a reply from the server, it'll say what you see. That must mean that it never got the reply for some reason...

Have you tried leaving the world and going back again (after the time that you mentioned)?

**Comment by thebrightspark** [comment]
Closing this due to no more information
